 2019-06-23 22:53:02,111 [P6408/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.13.2 application starting on KHATIBI
 2019-06-23 22:53:02,333 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2019-06-23 22:53:02,371 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 38ms)
 2019-06-23 22:53:02,491 [P6408/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2019-06-23 22:53:02,492 [P6408/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2019-06-23 22:53:02,494 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 22:53:04,281 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1787ms)
 2019-06-23 22:53:04,281 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2019-06-23 22:53:04,288 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 7ms)
 2019-06-23 22:53:04,307 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 22:53:04,308 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 22:53:04,308 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2019-06-23 22:53:04,355 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 47ms)
 2019-06-23 22:53:04,356 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 22:53:04,356 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 22:53:04,357 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2019-06-23 22:53:04,365 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 8ms)
 2019-06-23 22:53:04,383 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 22:53:04,383 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 22:53:04,383 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2019-06-23 22:53:04,390 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 6ms)
 2019-06-23 22:53:04,391 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 22:53:04,391 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 22:53:04,391 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2019-06-23 22:53:04,399 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 7ms)
 2019-06-23 22:53:07,926 [P6408/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: 78.46.29.99,1430, InitialCatalog: 1682_VitinqDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Login failed for user '1682_vitinquser'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:88b6847c-f53c-4275-97f5-d3f2037586f4
Error Number:18456,State:1,Class:14
 2019-06-23 22:53:07,927 [P6408/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-06-23 22:53:07,971 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Extensions.Models.Custom.Extract.PropertyExtractBase
 2019-06-23 22:53:07,988 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Extensions.Models.Custom.Extract.PropertyExtractBase (took 16ms)
 2019-06-23 22:53:08,296 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2019-06-23 22:53:08,305 [P6408/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 8ms)
 2019-06-23 22:53:08,316 [P6408/D2/T1] INFO  Epiphany.SeoMetadata.SeoMetadataStartup - Configured SeoMetadataUrlSegmentProvider
 2019-06-23 22:53:08,383 [P6408/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: 78.46.29.99,1430, InitialCatalog: 1682_VitinqDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Login failed for user '1682_vitinquser'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:88b6847c-f53c-4275-97f5-d3f2037586f4
Error Number:18456,State:1,Class:14
 2019-06-23 22:53:08,383 [P6408/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-06-23 22:53:09,385 [P6408/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: 78.46.29.99,1430, InitialCatalog: 1682_VitinqDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Login failed for user '1682_vitinquser'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:88b6847c-f53c-4275-97f5-d3f2037586f4
Error Number:18456,State:1,Class:14
 2019-06-23 22:53:09,386 [P6408/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-06-23 22:53:10,387 [P6408/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: 78.46.29.99,1430, InitialCatalog: 1682_VitinqDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Login failed for user '1682_vitinquser'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:88b6847c-f53c-4275-97f5-d3f2037586f4
Error Number:18456,State:1,Class:14
 2019-06-23 22:53:10,388 [P6408/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-06-23 22:53:11,389 [P6408/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: 78.46.29.99,1430, InitialCatalog: 1682_VitinqDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Login failed for user '1682_vitinquser'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:88b6847c-f53c-4275-97f5-d3f2037586f4
Error Number:18456,State:1,Class:14
 2019-06-23 22:53:11,390 [P6408/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-06-23 22:53:12,391 [P6408/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: 78.46.29.99,1430, InitialCatalog: 1682_VitinqDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Login failed for user '1682_vitinquser'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:88b6847c-f53c-4275-97f5-d3f2037586f4
Error Number:18456,State:1,Class:14
 2019-06-23 22:53:12,392 [P6408/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-06-23 22:53:13,769 [P6408/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: 78.46.29.99,1430, InitialCatalog: 1682_VitinqDB. Exception: System.Data.SqlClient.SqlException (0x80131904): Login failed for user '1682_vitinquser'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:3314bc83-ddd7-4d17-b848-9da0ef87fcaf
Error Number:18456,State:1,Class:14
 2019-06-23 22:53:13,770 [P6408/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2019-06-23 22:53:13,778 [P6408/D2/T1] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
Umbraco.Core.Exceptions.UmbracoStartupFailedException: Umbraco cannot start. A connection string is configured but Umbraco cannot connect to the database.
   at Umbraco.Core.CoreBootManager.EnsureDatabaseConnection()
   at Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete)
   at Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete)
   at Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
   at Umbraco.Core.UmbracoApplicationBase.Application_Start(Object sender, EventArgs e)
 2019-06-23 22:53:23,842 [P6408/D2/T8] INFO  Umbraco.Core.MainDom - Stopping...
 2019-06-23 22:53:23,847 [P6408/D2/T8] INFO  Umbraco.Web.ExamineStartup - Examine shutting down
 2019-06-23 22:53:25,158 [P6408/D2/T8] INFO  Umbraco.Web.ExamineStartup - Complete (took 1311ms)
 2019-06-23 22:53:25,159 [P6408/D2/T8] INFO  Umbraco.Core.MainDom - Released MainDom.
 2019-06-23 22:53:55,335 [P6408/D2/T6] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: InitializationError

_shutDownMessage=Initialization Error
HostingEnvironment initiated shutdown
HostingEnvironment caused shutdown

_shutDownStack=   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   at System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   at System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   at System.Web.HttpRuntime.AppDomainShutdownTimerCallback(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
 2019-06-23 23:15:32,341 [P9636/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.13.2 application starting on KHATIBI
 2019-06-23 23:15:32,364 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2019-06-23 23:15:32,375 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 11ms)
 2019-06-23 23:15:32,441 [P9636/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2019-06-23 23:15:32,442 [P9636/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2019-06-23 23:15:32,444 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:15:32,874 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 430ms)
 2019-06-23 23:15:32,875 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2019-06-23 23:15:32,885 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 10ms)
 2019-06-23 23:15:32,909 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:15:32,910 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 1ms)
 2019-06-23 23:15:32,910 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2019-06-23 23:15:32,920 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 9ms)
 2019-06-23 23:15:32,921 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:15:32,921 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:15:32,921 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2019-06-23 23:15:32,930 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 8ms)
 2019-06-23 23:15:32,952 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:15:32,953 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:15:32,953 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2019-06-23 23:15:32,963 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 9ms)
 2019-06-23 23:15:32,964 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:15:32,965 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:15:32,965 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2019-06-23 23:15:32,975 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 10ms)
 2019-06-23 23:15:34,578 [P9636/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2019-06-23 23:15:34,858 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Extensions.Models.Custom.Extract.PropertyExtractBase
 2019-06-23 23:15:34,869 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Extensions.Models.Custom.Extract.PropertyExtractBase (took 11ms)
 2019-06-23 23:15:34,925 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2019-06-23 23:15:34,938 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 12ms)
 2019-06-23 23:15:34,952 [P9636/D2/T1] INFO  Epiphany.SeoMetadata.SeoMetadataStartup - Configured SeoMetadataUrlSegmentProvider
 2019-06-23 23:15:35,018 [P9636/D2/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2019-06-23 23:15:35,358 [P9636/D2/T1] WARN  Umbraco.Core.Sync.DatabaseServerMessenger - No last synced Id found, this generally means this is a new server/install. The server will build its caches and indexes, and then adjust its last synced Id to the latest found in the database and maintain cache updates based on that Id.
 2019-06-23 23:15:35,403 [P9636/D2/T1] INFO  umbraco.content - Load Xml from file...
 2019-06-23 23:15:35,441 [P9636/D2/T1] INFO  umbraco.content - Loaded Xml from file.
 2019-06-23 23:15:35,468 [P9636/D2/T1] INFO  umbraco.content - Loading content from database...
 2019-06-23 23:15:36,617 [P9636/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalIndexSet to be unlocked since it was left in a locked state
 2019-06-23 23:15:36,619 [P9636/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index ExternalIndexSet to be unlocked since it was left in a locked state
 2019-06-23 23:15:36,623 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - Rebuilding index, Provider=InternalMemberIndexer, NodeId=-1
 2019-06-23 23:15:36,714 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - member, Provider=InternalMemberIndexer, NodeId=-1
 2019-06-23 23:15:36,919 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - member, took 204ms, Provider=InternalMemberIndexer, NodeId=-1
 2019-06-23 23:15:36,920 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - Rebuilding index, Provider=InternalIndexer, NodeId=-1
 2019-06-23 23:15:36,956 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - content, Provider=InternalIndexer, NodeId=-1
 2019-06-23 23:15:37,418 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:15:37,419 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:15:37,419 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2019-06-23 23:15:37,463 [P9636/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 42ms)
 2019-06-23 23:15:37,771 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - content, took 813ms, Provider=InternalIndexer, NodeId=-1
 2019-06-23 23:15:37,771 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - media, Provider=InternalIndexer, NodeId=-1
 2019-06-23 23:15:37,855 [P9636/D2/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:15:37,856 [P9636/D2/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:15:37,856 [P9636/D2/T14] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2019-06-23 23:15:37,870 [P9636/D2/T14] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 13ms)
 2019-06-23 23:15:38,009 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - media, took 238ms, Provider=InternalIndexer, NodeId=-1
 2019-06-23 23:15:38,009 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - Rebuilding index, Provider=ExternalIndexer, NodeId=-1
 2019-06-23 23:15:38,141 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - content, Provider=ExternalIndexer, NodeId=-1
 2019-06-23 23:15:38,273 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - content, took 131ms, Provider=ExternalIndexer, NodeId=-1
 2019-06-23 23:15:38,274 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - Start data queries - media, Provider=ExternalIndexer, NodeId=-1
 2019-06-23 23:15:38,347 [P9636/D2/T1] INFO  UmbracoExamine.DataServices.UmbracoLogService - PerformIndexAll - End data queries - media, took 73ms, Provider=ExternalIndexer, NodeId=-1
 2019-06-23 23:15:38,487 [P9636/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2019-06-23 23:15:38,489 [P9636/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2019-06-23 23:15:38,508 [P9636/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 6266ms)
 2019-06-23 23:15:40,002 [P9636/D2/T14] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: http://localhost:53834/vitinqpanel
 2019-06-23 23:15:40,004 [P9636/D2/T14] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost:53834/vitinqpanel (UmbracoModule request)
 2019-06-23 23:15:40,512 [P9636/D2/T14] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Started TryFindContent
 2019-06-23 23:15:40,602 [P9636/D2/T14] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Completed TryFindContent (took 89ms)
 2019-06-23 23:15:40,632 [P9636/D2/T15] INFO  umbraco.content - Save Xml to file...
 2019-06-23 23:15:40,638 [P9636/D2/T14] WARN  Umbraco.Web.UmbracoModule - Status code is 404 yet TrySkipIisCustomErrors is false - IIS will take over.
 2019-06-23 23:15:40,643 [P9636/D2/T15] INFO  umbraco.content - Saved Xml to file.
 2019-06-23 23:15:53,513 [P9636/D2/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:15:53,513 [P9636/D2/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:15:53,513 [P9636/D2/T14] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2019-06-23 23:15:53,521 [P9636/D2/T14] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 7ms)
 2019-06-23 23:15:53,790 [P9636/D2/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:15:53,790 [P9636/D2/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:15:53,790 [P9636/D2/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2019-06-23 23:15:53,797 [P9636/D2/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 6ms)
 2019-06-23 23:16:40,543 [P9636/D2/T16] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2019-06-22 23:16:40
 2019-06-23 23:17:01,578 [P9636/D2/T24] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username Saied.khatibi@gmail.com from IP address ::1
 2019-06-23 23:17:01,580 [P9636/D2/T24] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: saied.khatibi@gmail.com logged in from IP address ::1
 2019-06-23 23:17:02,422 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:17:02,422 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:17:02,422 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ITree
 2019-06-23 23:17:02,430 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ITree (took 7ms)
 2019-06-23 23:17:02,447 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:17:02,447 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:17:02,447 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2019-06-23 23:17:02,447 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2019-06-23 23:17:02,451 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:17:02,452 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:17:02,452 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree
 2019-06-23 23:17:02,461 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree (took 8ms)
 2019-06-23 23:17:02,489 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:17:02,489 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:17:02,490 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication
 2019-06-23 23:17:02,606 [P9636/D2/T18] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication (took 116ms)
 2019-06-23 23:22:44,042 [P9636/D2/T53] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:22:44,042 [P9636/D2/T53] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:22:44,042 [P9636/D2/T53] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ICacheRefresher
 2019-06-23 23:22:44,050 [P9636/D2/T53] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ICacheRefresher (took 8ms)
 2019-06-23 23:23:10,032 [P9636/D2/T53] INFO  umbraco.content - Save Xml to file...
 2019-06-23 23:23:10,043 [P9636/D2/T53] INFO  umbraco.content - Saved Xml to file.
 2019-06-23 23:24:00,573 [P9636/D2/T73] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Started TryFindContent
 2019-06-23 23:24:00,590 [P9636/D2/T73] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Completed TryFindContent (took 16ms)
 2019-06-23 23:24:02,994 [P9636/D2/T73] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:24:02,995 [P9636/D2/T73] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:24:02,995 [P9636/D2/T73] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Deploy.IServiceConnector
 2019-06-23 23:24:03,003 [P9636/D2/T73] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Deploy.IServiceConnector (took 7ms)
 2019-06-23 23:26:53,291 [P9636/D2/T52] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Started TryFindContent
 2019-06-23 23:26:53,298 [P9636/D2/T52] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Completed TryFindContent (took 7ms)
 2019-06-23 23:34:42,971 [P4464/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.13.2 application starting on KHATIBI
 2019-06-23 23:34:42,994 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2019-06-23 23:34:43,006 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 12ms)
 2019-06-23 23:34:43,076 [P4464/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2019-06-23 23:34:43,078 [P4464/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2019-06-23 23:34:43,080 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:34:43,451 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 370ms)
 2019-06-23 23:34:43,452 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2019-06-23 23:34:43,459 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 7ms)
 2019-06-23 23:34:43,481 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:34:43,481 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:34:43,482 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2019-06-23 23:34:43,489 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 6ms)
 2019-06-23 23:34:43,490 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:34:43,490 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:34:43,490 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2019-06-23 23:34:43,497 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 7ms)
 2019-06-23 23:34:43,513 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:34:43,513 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:34:43,514 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2019-06-23 23:34:43,521 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 7ms)
 2019-06-23 23:34:43,522 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:34:43,522 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:34:43,522 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2019-06-23 23:34:43,529 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 6ms)
 2019-06-23 23:34:45,146 [P4464/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2019-06-23 23:34:45,315 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Extensions.Models.Custom.Extract.PropertyExtractBase
 2019-06-23 23:34:45,325 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Extensions.Models.Custom.Extract.PropertyExtractBase (took 9ms)
 2019-06-23 23:34:45,377 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Models.PublishedContent.PublishedContentModel
 2019-06-23 23:34:45,386 [P4464/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Models.PublishedContent.PublishedContentModel (took 8ms)
 2019-06-23 23:34:45,396 [P4464/D2/T1] INFO  Epiphany.SeoMetadata.SeoMetadataStartup - Configured SeoMetadataUrlSegmentProvider
 2019-06-23 23:34:45,464 [P4464/D2/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2019-06-23 23:34:45,840 [P4464/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2019-06-23 23:34:45,842 [P4464/D2/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 3
 2019-06-23 23:34:45,865 [P4464/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 2984ms)
 2019-06-23 23:34:45,868 [P4464/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalMemberIndexSet to be unlocked since it was left in a locked state
 2019-06-23 23:34:45,870 [P4464/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index InternalIndexSet to be unlocked since it was left in a locked state
 2019-06-23 23:34:45,870 [P4464/D2/T1] INFO  Umbraco.Web.ExamineStartup - Forcing index ExternalIndexSet to be unlocked since it was left in a locked state
 2019-06-23 23:34:46,072 [P4464/D2/T11] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - New ApplicationUrl detected: http://localhost:53834/vitinqpanel
 2019-06-23 23:34:46,074 [P4464/D2/T11] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://localhost:53834/vitinqpanel (UmbracoModule request)
 2019-06-23 23:34:46,391 [P4464/D2/T11] INFO  umbraco.content - Load Xml from file...
 2019-06-23 23:34:46,394 [P4464/D2/T11] INFO  umbraco.content - Loaded Xml from file.
 2019-06-23 23:34:46,582 [P4464/D2/T11] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Started TryFindContent
 2019-06-23 23:34:46,583 [P4464/D2/T12] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Started TryFindContent
 2019-06-23 23:34:47,244 [P4464/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:34:47,244 [P4464/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:34:47,244 [P4464/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2019-06-23 23:34:47,251 [P4464/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 6ms)
 2019-06-23 23:34:47,446 [P4464/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:34:47,447 [P4464/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:34:47,448 [P4464/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2019-06-23 23:34:47,462 [P4464/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 14ms)
 2019-06-23 23:34:48,727 [P4464/D2/T11] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Completed TryFindContent (took 2144ms)
 2019-06-23 23:34:48,727 [P4464/D2/T12] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Completed TryFindContent (took 2144ms)
 2019-06-23 23:34:48,806 [P4464/D2/T11] WARN  Umbraco.Web.UmbracoModule - Status code is 404 yet TrySkipIisCustomErrors is false - IIS will take over.
 2019-06-23 23:34:51,115 [P4464/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:34:51,115 [P4464/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:34:51,115 [P4464/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.Deploy.IServiceConnector
 2019-06-23 23:34:51,124 [P4464/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.Deploy.IServiceConnector (took 8ms)
 2019-06-23 23:35:00,963 [P4464/D2/T11] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Started TryFindContent
 2019-06-23 23:35:00,966 [P4464/D2/T11] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Completed TryFindContent (took 3ms)
 2019-06-23 23:35:46,578 [P4464/D2/T16] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2019-06-22 23:35:46
 2019-06-23 23:48:31,672 [P4464/D2/T52] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Started TryFindContent
 2019-06-23 23:48:31,672 [P4464/D2/T52] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Completed TryFindContent (took 0ms)
 2019-06-23 23:48:31,674 [P4464/D2/T52] WARN  Umbraco.Web.UmbracoModule - Status code is 404 yet TrySkipIisCustomErrors is false - IIS will take over.
 2019-06-23 23:48:38,171 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:48:38,171 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:48:38,171 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2019-06-23 23:48:38,182 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 10ms)
 2019-06-23 23:48:38,264 [P4464/D2/T60] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:48:38,264 [P4464/D2/T60] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:48:38,265 [P4464/D2/T60] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2019-06-23 23:48:38,272 [P4464/D2/T60] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 7ms)
 2019-06-23 23:48:42,562 [P4464/D2/T61] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username Saied.khatibi@gmail.com from IP address ::1
 2019-06-23 23:48:42,563 [P4464/D2/T61] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: saied.khatibi@gmail.com logged in from IP address ::1
 2019-06-23 23:48:43,346 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:48:43,346 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:48:43,347 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ITree
 2019-06-23 23:48:43,358 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ITree (took 11ms)
 2019-06-23 23:48:43,380 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:48:43,381 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:48:43,381 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2019-06-23 23:48:43,381 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2019-06-23 23:48:43,390 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:48:43,390 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:48:43,391 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree
 2019-06-23 23:48:43,401 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree (took 10ms)
 2019-06-23 23:48:43,423 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:48:43,423 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:48:43,424 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication
 2019-06-23 23:48:43,441 [P4464/D2/T65] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication (took 17ms)
 2019-06-23 23:49:20,906 [P4464/D2/T52] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2019-06-23 23:49:20,907 [P4464/D2/T52] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2019-06-23 23:49:20,907 [P4464/D2/T52] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ICacheRefresher
 2019-06-23 23:49:20,915 [P4464/D2/T52] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ICacheRefresher (took 8ms)
 2019-06-23 23:49:40,133 [P4464/D2/T71] INFO  umbraco.content - Save Xml to file...
 2019-06-23 23:49:40,226 [P4464/D2/T71] INFO  umbraco.content - Saved Xml to file.
 2019-06-23 23:49:41,704 [P4464/D2/T61] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Started TryFindContent
 2019-06-23 23:49:41,720 [P4464/D2/T61] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Completed TryFindContent (took 16ms)
 2019-06-23 23:49:44,893 [P4464/D2/T52] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Started TryFindContent
 2019-06-23 23:49:44,896 [P4464/D2/T52] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Completed TryFindContent (took 3ms)
 2019-06-23 23:49:54,201 [P4464/D2/T52] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Started TryFindContent
 2019-06-23 23:49:54,204 [P4464/D2/T52] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Completed TryFindContent (took 3ms)
 2019-06-23 23:49:57,763 [P4464/D2/T52] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Started TryFindContent
 2019-06-23 23:49:57,765 [P4464/D2/T52] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Completed TryFindContent (took 2ms)
 2019-06-23 23:50:03,983 [P4464/D2/T67] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Started TryFindContent
 2019-06-23 23:50:03,988 [P4464/D2/T67] INFO  Umbraco.Extensions.ContentFinders.MultilingualContentFinder - Completed TryFindContent (took 4ms)
